// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbrirModulo(arg1) {
  return window['go']['main']['App']['AbrirModulo'](arg1);
}

export function BuscarEmpresas() {
  return window['go']['main']['App']['BuscarEmpresas']();
}

export function CheckStatusConexao() {
  return window['go']['main']['App']['CheckStatusConexao']();
}

export function ConfirmarEntrada(arg1) {
  return window['go']['main']['App']['ConfirmarEntrada'](arg1);
}

export function DeletarEmpresa(arg1) {
  return window['go']['main']['App']['DeletarEmpresa'](arg1);
}

export function DeletarEnderecamento(arg1) {
  return window['go']['main']['App']['DeletarEnderecamento'](arg1);
}

export function DesvincularSimilar(arg1, arg2) {
  return window['go']['main']['App']['DesvincularSimilar'](arg1, arg2);
}

export function EscutarBanco() {
  return window['go']['main']['App']['EscutarBanco']();
}

export function ExcluirCategoria(arg1) {
  return window['go']['main']['App']['ExcluirCategoria'](arg1);
}

export function ExcluirFuncao(arg1) {
  return window['go']['main']['App']['ExcluirFuncao'](arg1);
}

export function ExcluirMarca(arg1) {
  return window['go']['main']['App']['ExcluirMarca'](arg1);
}

export function ExcluirPerfilFiscal(arg1) {
  return window['go']['main']['App']['ExcluirPerfilFiscal'](arg1);
}

export function ExcluirProduto(arg1) {
  return window['go']['main']['App']['ExcluirProduto'](arg1);
}

export function ExcluirSubcategoria(arg1) {
  return window['go']['main']['App']['ExcluirSubcategoria'](arg1);
}

export function ExcluirUsuario(arg1) {
  return window['go']['main']['App']['ExcluirUsuario'](arg1);
}

export function GetModuloInicial() {
  return window['go']['main']['App']['GetModuloInicial']();
}

export function GetProximoIDUsuario() {
  return window['go']['main']['App']['GetProximoIDUsuario']();
}

export function GravarEmpresa(arg1) {
  return window['go']['main']['App']['GravarEmpresa'](arg1);
}

export function GravarEnderecamento(arg1) {
  return window['go']['main']['App']['GravarEnderecamento'](arg1);
}

export function ImportarMarcasCSV(arg1) {
  return window['go']['main']['App']['ImportarMarcasCSV'](arg1);
}

export function ImportarXML() {
  return window['go']['main']['App']['ImportarXML']();
}

export function ListarCategorias() {
  return window['go']['main']['App']['ListarCategorias']();
}

export function ListarEnderecamentos(arg1) {
  return window['go']['main']['App']['ListarEnderecamentos'](arg1);
}

export function ListarEntradas() {
  return window['go']['main']['App']['ListarEntradas']();
}

export function ListarFornecedores() {
  return window['go']['main']['App']['ListarFornecedores']();
}

export function ListarFuncoes() {
  return window['go']['main']['App']['ListarFuncoes']();
}

export function ListarMarcas() {
  return window['go']['main']['App']['ListarMarcas']();
}

export function ListarPerfisFiscais() {
  return window['go']['main']['App']['ListarPerfisFiscais']();
}

export function ListarProdutos() {
  return window['go']['main']['App']['ListarProdutos']();
}

export function ListarSubcategorias() {
  return window['go']['main']['App']['ListarSubcategorias']();
}

export function ListarUnidadesMedida() {
  return window['go']['main']['App']['ListarUnidadesMedida']();
}

export function ListarUsuarios() {
  return window['go']['main']['App']['ListarUsuarios']();
}

export function MaximizarJanela() {
  return window['go']['main']['App']['MaximizarJanela']();
}

export function ObterEntrada(arg1) {
  return window['go']['main']['App']['ObterEntrada'](arg1);
}

export function ObterProximoIdProduto() {
  return window['go']['main']['App']['ObterProximoIdProduto']();
}

export function ResetarSenha(arg1, arg2) {
  return window['go']['main']['App']['ResetarSenha'](arg1, arg2);
}

export function SalvarCategoria(arg1) {
  return window['go']['main']['App']['SalvarCategoria'](arg1);
}

export function SalvarEntrada(arg1) {
  return window['go']['main']['App']['SalvarEntrada'](arg1);
}

export function SalvarFuncao(arg1) {
  return window['go']['main']['App']['SalvarFuncao'](arg1);
}

export function SalvarMarca(arg1, arg2) {
  return window['go']['main']['App']['SalvarMarca'](arg1, arg2);
}

export function SalvarPerfilFiscal(arg1) {
  return window['go']['main']['App']['SalvarPerfilFiscal'](arg1);
}

export function SalvarProduto(arg1) {
  return window['go']['main']['App']['SalvarProduto'](arg1);
}

export function SalvarSubcategoria(arg1, arg2) {
  return window['go']['main']['App']['SalvarSubcategoria'](arg1, arg2);
}

export function SalvarUsuario(arg1) {
  return window['go']['main']['App']['SalvarUsuario'](arg1);
}

export function VincularSimilar(arg1, arg2) {
  return window['go']['main']['App']['VincularSimilar'](arg1, arg2);
}
