// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {motor} from '../models';

export function AbrirModulo(arg1:string):Promise<void>;

export function BuscarEmpresas():Promise<Array<motor.Empresa>>;

export function CheckStatusConexao():Promise<Record<string, any>>;

export function ConfirmarEntrada(arg1:number):Promise<string>;

export function DeletarEmpresa(arg1:number):Promise<boolean>;

export function DeletarEnderecamento(arg1:number):Promise<string>;

export function DesvincularSimilar(arg1:number,arg2:number):Promise<string>;

export function EscutarBanco():Promise<void>;

export function ExcluirCategoria(arg1:number):Promise<string>;

export function ExcluirFuncao(arg1:number):Promise<string>;

export function ExcluirMarca(arg1:number):Promise<string>;

export function ExcluirPerfilFiscal(arg1:number):Promise<string>;

export function ExcluirProduto(arg1:number):Promise<string>;

export function ExcluirSubcategoria(arg1:number):Promise<string>;

export function ExcluirUsuario(arg1:number):Promise<string>;

export function GetModuloInicial():Promise<string>;

export function GetProximoIDUsuario():Promise<number>;

export function GravarEmpresa(arg1:motor.Empresa):Promise<string>;

export function GravarEnderecamento(arg1:motor.Enderecamento):Promise<number>;

export function ImportarMarcasCSV(arg1:string):Promise<string>;

export function ImportarXML():Promise<motor.Entrada>;

export function ListarCategorias():Promise<Array<motor.Categoria>>;

export function ListarEnderecamentos(arg1:number):Promise<Array<motor.Enderecamento>>;

export function ListarEntradas():Promise<Array<motor.Entrada>>;

export function ListarFornecedores():Promise<Array<motor.Fornecedor>>;

export function ListarFuncoes():Promise<Array<motor.Funcao>>;

export function ListarMarcas():Promise<Array<motor.Marca>>;

export function ListarPerfisFiscais():Promise<Array<motor.PerfilFiscal>>;

export function ListarProdutos():Promise<Array<motor.Produto>>;

export function ListarSubcategorias():Promise<Array<motor.Subcategoria>>;

export function ListarUnidadesMedida():Promise<Array<motor.UnidadeMedida>>;

export function ListarUsuarios():Promise<Array<motor.Usuario>>;

export function MaximizarJanela():Promise<void>;

export function ObterEntrada(arg1:number):Promise<motor.Entrada>;

export function ObterProximoIdProduto():Promise<number>;

export function ResetarSenha(arg1:number,arg2:string):Promise<string>;

export function SalvarCategoria(arg1:string):Promise<string>;

export function SalvarEntrada(arg1:motor.Entrada):Promise<string>;

export function SalvarFuncao(arg1:motor.Funcao):Promise<string>;

export function SalvarMarca(arg1:string,arg2:number):Promise<string>;

export function SalvarPerfilFiscal(arg1:motor.PerfilFiscal):Promise<string>;

export function SalvarProduto(arg1:motor.Produto):Promise<string>;

export function SalvarSubcategoria(arg1:number,arg2:string):Promise<string>;

export function SalvarUsuario(arg1:motor.Usuario):Promise<string>;

export function VincularSimilar(arg1:number,arg2:number):Promise<string>;
